# nombre de la carpeta en la que se generará el sitio 
name = "Mezagini"

# la página notion.so desde la que se está analizando. Esta página se convertirá en el index.html 
# del sitio generado, y loconotion analizará todas las subpáginas presentes en la página 
page = "https://www.notion.so/danielmeza/Mezagini-0ccb8d1947f14850be863d5f1027776c"

# aplique opcionalmente el modo oscuro de la noción, elimine la línea a continuación para usar el modo de luz predeterminado 
theme = "dark"
