# nombre de la carpeta en la que se generará el sitio 
name = "Mezagini"

# la página notion.so desde la que se está analizando. Esta página se convertirá en el index.html 
# del sitio generado, y loconotion analizará todas las subpáginas presentes en la página 
page = "https://www.notion.so/danielmeza/Mezagini-7f23f27679004f0da33239e909616c85"

# aplique opcionalmente el modo oscuro de la noción, elimine la línea a continuación para usar el modo de luz predeterminado 
theme = "dark"

## Global Site Settings ##
# this [site] table defines override settings for the whole site
# later on we will see how to define settings for a single page
[site]
  ## Custom Meta Tags ##
  # defined as an array of tables (double square brackets)
  # each key in the table maps to an atttribute in the tag
  # the following adds the tag <meta name="title" content="Loconotion Test Site"/>
  [[site.meta]]
  name = "title"
  content = "Loconotion Test Site"
  [[site.meta]]
  name = "description"
  content = "A static site generated from a Notion.so page using Loconotion"
